version: "3.8"

services:

  # --- DATABASE
  mysql-main:
    image: mysql:8
    container_name: "mysql-main"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped 
    env_file:
      - ./docker/env/docker.mysql-main.env
    ports:
      - "${HOST_MYSQL_PORT}:3306"
    volumes:
      - ./docker/volumes/mysql-main:/var/lib/mysql

  # --- SERVER
  server-main:
    container_name: "server-main"
    depends_on:
      - mysql-main
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: 
      - ./docker/env/docker.server-main.env
    ports:
      - ${HOST_SERVER_PORT}:${DOCKER_SERVER_PORT}
    environment:
      - PORT=${DOCKER_SERVER_PORT}
      - MYSQL_HOST=mysql-main
    stdin_open: true
    tty: true
