version: "3.8"

services:
  mysql-main:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysql-main"
    restart: unless-stopped 
    env_file:
      - ./docker/env/docker.mysql-main.env
    ports:
      - "33007:3306"
    volumes:
      - ./docker/volumes/mysql-main:/var/lib/mysql
  server-main:
    depends_on:
      - mysql-main
    container_name: "server-main"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: 
      - ./docker/env/docker.server-main.env
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
