version: "3.8"

services:
  mysql-main:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysql-main"
    restart: unless-stopped 
    env_file:
      - ../env/docker.env
    ports:
      - "33007:3306"
    volumes:
      - ../volumes/mysql-main:/var/lib/mysql